# Generated by Django 5.1.5 on 2025-01-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeapp', '0002_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.BooleanField(),
        ),
    ]
